# Generated by Django 5.1.1 on 2025-07-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_likedlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedlisting',
            old_name='like_listing',
            new_name='like_listing_date',
        ),
    ]
